version: '3.3'

services:
    zoo:
        image: local-zoo
        build:
            context: '.'
            dockerfile: ./zoo_dockerfile
        container_name: zoo
        volumes:
            - ./zoo.cfg:/conf/zoo.cfg
        
    solr:
        image: local-solr
        build:
            context: '.'
            dockerfile: ./solr_dockerfile
        container_name: solr
        ports:
            - "8983:8983"
        environment:
            - ZK_HOST=zoo:2181
        depends_on: 
            - zoo
            